<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleDataMaker.Domain\SampleDataMaker.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SQL\SqlServer\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
  </ItemGroup>

</Project>
