<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\ColumnSampleDataSelectionItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleDataMaker.Domain\SampleDataMaker.Domain.csproj" />
    <ProjectReference Include="..\SampleDataMaker.Infrastructure\SampleDataMaker.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="log4.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="master-data\sample-data.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
